### ISSUE TITLE
How do I add typescript support?

### ISSUE THREAD

**Issue by andersforsell** [web-padawan/polymer3-webpack-starter#15]
Have you looked into adding typescript support?
Some nice features like decorators can be used, esp. with lit-element.

**Comment by web-padawan** [comment]
This project is meant for developers who want to quickly start with ES modules.
For TS support, consider using another community starter kit instead: 
https://github.com/Dabolus/polymer3-webpack-starter-kit

**Comment by web-padawan** [comment]
Closing as answered per above comment.
