### ISSUE TITLE
[Question] How to implement pagination?

### ISSUE THREAD

**Issue by tiho2** [web-padawan/polymer3-webpack-starter#16]
Existing examples refer to polymer 2 style. Is the pagination available for free vaadin-grid polymer 3 web component?

**Comment by moderndeveloperllc** [comment]
@tiho2 https://cdn.vaadin.com/vaadin-grid/5.2.2/demo/#grid-pagination-demos has ES6/Polymer 3-style pagination. You would want to include the `<style>` info in your
```
static get template() {
    return html``;
``` 
block and perhaps call `updateItemsFromPage()` from `ready()` or similar.

**Comment by tiho2** [comment]
@moderndeveloperllc: Thanks!
I'll investigate it further.

**Comment by web-padawan** [comment]
The API for all the Vaadin components are exactly the same both for Polymer 2 and 3.
Closing this issue per above comment, feel free to continue discussion in the vaadin-grid issue:
https://github.com/vaadin/vaadin-grid/issues/452

**Comment by tiho2** [comment]
@moderndeveloperllc @all Is the souce code available for these demos?
