### ISSUE TITLE
Different webpack devtool for different env

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-padawan/polymer3-webpack-starter#3]
https://github.com/web-padawan/polymer3-webpack-starter/blob/b946a107d1ff58b6ebbfa33378a63a67ed21235b/webpack.config.js#L69

Not a webpack expert by any means, but it looks like it would be better to use this config in the dev environment and something like `nosources-source-map` for production. 

Really starting to look nice!

**Comment by web-padawan** [comment]
Thanks for the issue! I checked with the docs and looks like it is a valid point: https://webpack.js.org/configuration/devtool/

Will try out a different options and choose a different option for production.

**Comment by web-padawan** [comment]
Fixed in d4dd11d. Thank you once again for helping me improve this starter!
