### ISSUE TITLE
[Question] babelHelpers is not defined on ES6 supported browser

### ISSUE THREAD

**Issue by jorgecasar** [web-padawan/polymer3-webpack-starter#31]
I'm trying to integrate this webpack development flow but I'm getting this error when I run `npm run dev` on my app using litElement and Polymer 3.x components.

```
updating-element.ts:614 Uncaught ReferenceError: babelHelpers is not defined
    at HTMLElement._enqueueUpdate (updating-element.ts:614)
    at HTMLElement.requestUpdate (updating-element.ts:606)`


  | _enqueueUpdate | @ | updating-element.ts:614
-- | -- | -- | --
  | requestUpdate | @ | updating-element.ts:606
  | set | @ | updating-element.ts:307
  | MyApp | @ | my-app.js:237
  | ./src/app/my-app.js?babel-target=es6 | @ | my-app.js:465
  | __webpack_require__ | @ | bootstrap:63
  | ./src/index.js?babel-target=es6 | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:63
  | 0 | @ | page-view-element.js:17
  | __webpack_require__ | @ | bootstrap:63
  | (anonymous) | @ | bootstrap:195
  | (anonymous) | @ | bootstrap:195
```

The `babelHelpers` appear 12 times in `main.XXXXX.js` file. Do you have any idea of why it's happening?

**Comment by jorgecasar** [comment]
Taking a deeper look, one reason could be it replace the `Object.entries` by a Babel helper in the ES6 version. I will try with different target configurations

**Comment by moderndeveloperllc** [comment]
@jorgecasar It may be possible that Babel is doing that since `Object.entries` is ES2017 and the `es6` target is going back `'last 3 Safari major versions', 'last 3 iOS major versions'` which pulls in Safari 10 that doesn't have that defined. If you aren't overly concerned with the Safari 10.1 module bug, you can change those entries to `last 2` for each and that should keep Babel helpers from needing to be substituted.

Alternatively, remove the `nomodule` from the call in `index.html`, but that's a heavy file that ES6 browsers wont normally need.

**Comment by moderndeveloperllc** [comment]
> Taking a deeper look, one reason could be it replace the `Object.entries` by a Babel helper in the ES6 version. I will try with different target configurations

I use https://browserl.ist/ and http://kangax.github.io/compat-table/es2016plus/ to check functionality and what targets I want. Right now module/nomodule is a good split, but eventually you may need to have a babel-helpers generated for each build if you want to start using ES2017 and beyond.

**Comment by moderndeveloperllc** [comment]
@jorgecasar Did you fine a target config that worked for you?

**Comment by jorgecasar** [comment]
@moderndeveloperllc yes, finally I used:

```
targets: {
  es6: {
    browsers: [
      'Chrome >= 61',
      'Firefox >= 60',
      'Safari >= 11',
      'iOS >= 11',
      'Edge >= 18',
    ],
    tagAssetsWithKey: false,
    esModule: true
  },
  es5: {
    browsers: ['defaults'],
    tagAssetsWithKey: true,
    noModule: true
  }
}
```
