### ISSUE TITLE
Route config - action or bundle?

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-padawan/polymer3-webpack-starter#4]
https://github.com/web-padawan/polymer3-webpack-starter/blob/4d9de00cc3fafbd9e46d24b11a00d0a7d3f12a14/src/routes/config.js#L14-L16

Can this now just be `bundle`, or will that not work well with Webpack?

(Yes, this is my, "What's Vaadin doing recently" hour :eyes:)

**Comment by web-padawan** [comment]
Good question. Actually, one of the ideas was to allow bundle accept a function also. But currently, for Webpack the recommended way is to import files like this (these "magic comments" are not required).
You can find more info in their [dynamic import](https://webpack.js.org/api/module-methods/#import-) docs, but in short here is the key:

> Fully dynamic statements, such as import(foo), will fail because webpack requires at least some file location information.

This is why "bundle" feature is not using dynamic imports. Another thing is that it does not take into account the hashes added by Webpack to the file names. So, it is better to use `bundle` in the environments other than Webpack.

**Comment by moderndeveloperllc** [comment]
Thanks. I keep forgetting how webpack looks for things to substitute. I was thinking it would pick up
```
bundle: /* webpackChunkName: "list" */ '../views/employee-list'
```

**Comment by web-padawan** [comment]
Yes, this is how it works. I'm going to add more docs to the Readme in this repo, and looks like this use case should be also covered, especially for newcomers.
