### ISSUE TITLE
Module not found: TypeError: Cannot read property 'descriptionFileRoot' of undefined

### ISSUE THREAD

**Issue by marko-ignjatovic** [web-padawan/polymer3-webpack-starter#40]
I got this error after I typed 'npm run dev'

`ERROR in (webpack)-dev-server/client?http://0.0.0.0:3000
[1] Module not found: TypeError: Cannot read property 'descriptionFileRoot' of undefined
[1]  @ (webpack)-dev-server/client?http://0.0.0.0:3000 76:17-67
[1]  @ multi (webpack)-dev-server/client?http://0.0.0.0:3000#babel-target=es6 ./src?babel-target=es6`

**Comment by web-padawan** [comment]
I have updated all dependencies, and I cannot reproduce the error.
Can you clone the repo again and try if the problem persists?

**Comment by malikfaizanhaider** [comment]
Facing same issue.

**Comment by web-padawan** [comment]
Most likely the problem occurs in `webpack-babel-multi-target-plugin`:

https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/blob/5cdb617e008fada7921fc501a9c9c7b18dfbe7f0/src/targeting.plugin.ts#L364
