### ISSUE TITLE
[Research] Add HtmlWebpackDeployPlugin to webpack config

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-padawan/polymer3-webpack-starter#41]
I've been working on how to get 100% versioned `.js` files so I can set a long expires TTL for them at the browser level. Workbox may in fact negate the need for all this on modern browsers, but ServiceWorkers aren't in IE 11, etc. The problem I was having was with the `vendor/` files created for the babel helpers.

To inject dynamically generated file names, I found [HtmlWebpackDeployPlugin](https://github.com/jharris4/html-webpack-deploy-plugin). Basically, instead of having the files static in `index.html`, this will generate a hash for them and inject into the file along with doing CopyWebpackPlugin duties. My `index.html` now has no `<script>` tags as this plugin will append (with appropriate hashes of course):
```
<script type="text/javascript" src="./vendor/regenerator-runtime.min.5c703e8b.js" nomodule></script>
<script type="text/javascript" src="./vendor/babel-helpers.min.44b347e5.js" nomodule></script>
<script type="text/javascript" src="./vendor/babel-helpers-modern.min.34f7d93a.js"></script>
<script type="text/javascript" src="packages/@webcomponents/webcomponentsjs-2.2.10/webcomponents-loader.js"></script>
<script type="module" src="main.0f771508.js"></script>
<script type="text/javascript" src="main.es5.9b0631f2.js" nomodule></script>
```
You can see that this places `webcomponents-loader.js` (and associated bundle files) in a different path that includes the version - effectively setting a cache-busting parameter. It wouldn't take too much for a user to extend this to images and CSS too if needed.

This all may be too much for a starter template, but you might like it. I've uploaded the config to https://gist.github.com/moderndeveloperllc/a3774d2890fcff56d7b39b9883b0879f. It uses the 'modern' babel helper split and a few changes to the webpack-dev-server config, but those are just project specific so can be ignored. The main changes start with line 181.

**Comment by moderndeveloperllc** [comment]
@web-padawan FYI, I found out something important with IE 11. If you are going to load two files with babelHelpers defined, you need to load the `nomodule` version second, and include **_ALL_** the Polymer helper whitelist. Basically, IE 11 will define the `babelHelper` object, so if you have the "modern" version second, only those few methods get defined and break everything.

**Comment by web-padawan** [comment]
Closing as the repo is going to be archived.
