### ISSUE TITLE
Webpack routing regular expression - class call needed?

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-padawan/polymer3-webpack-starter#5]
https://github.com/web-padawan/polymer3-webpack-starter/blob/f7a75c6fdc222b3ca9a8830a3fe2f930fd066f1f/src/service-worker.js#L18

The docs indicate that this needs to be:
```
new RegExp('/\/vendor\/.*(?!loader).*\.js$/').
```

**Comment by web-padawan** [comment]
Thanks for the issue! I'm on vacation, will take a look on Friday.

**Comment by web-padawan** [comment]
Actually, the `new RegExp()` was not necessary, but the reg exp itself was incorrect. Fixed in db33fec
