### ISSUE TITLE
[Question] Page redirection

### ISSUE THREAD

**Issue by titilambert** [web-padawan/polymer3-webpack-starter#6]
First thanks for your work !
I have a quick question, How can I redirect to an other URL in a function ? I'm trying to avoid window.location =... or document.location = ... I guess it's something with vaadin router but I don't find the documentation :/
thanks for you answer

**Comment by web-padawan** [comment]
Thanks for the issue! Added the example in 1136aca
See https://github.com/web-padawan/polymer3-webpack-starter/blob/master/src/routes/utils.js#L5

Also, there are other ways to redirect user. See [Redirect demos](https://vaadin.github.io/vaadin-router/vaadin-router/demo/#vaadin-router-redirect-demos) for more detail.
