### ISSUE TITLE
[Question] ES6/ES6 Modules configuration?

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-padawan/polymer3-webpack-starter#8]
Hi there, me again. Are you thinking of creating non-transpiled versions of the build pipeline? Similar to how `polymer-build` is doing? I'm doing differential serving at the moment and like the idea of serving native code out to the browsers that can handle it. That, and not having to push out the babel-helpers and es5-adapter files is rather nice.

**Comment by web-padawan** [comment]
Hi, this should be doable and I was thinking about it. Probably not ES modules, but at least ES6. Will try to configure 2 builds.

**Comment by moderndeveloperllc** [comment]
Sorry I can't put in a PR myself about this. The build pipeline is something I can understand and help debug, but not yet actually create from nothing.

**Comment by web-padawan** [comment]
There is a draft in facebook/create-react-app@8295dbd

I will look into it hopefully next week or so, but in case if you are interested, feel free to try it out.

**Comment by moderndeveloperllc** [comment]
Oof. That's doing a bit of stuff I'm at the "o.k., if you say so" level of comprehending at the moment. It looks like they decided to make the split at whether or not a browser supports ES6 modules - a slightly more restrictive subset of browsers than just those that support ES6. It's a perfectly valid way to split if you don't want to do three or more configs. By splitting at modules/no modules, they are having to put in logic due to Safari that may make it overcomplicated. Your project, your call though.

**Comment by moderndeveloperllc** [comment]
Had any time to put thought into this? Being able to utilize `prpl-server` is a nice idea, though I wonder if that's too deeply tied to the output of the polymer toolchain to easily extricate to using this build process. I might be overthinking it though.

**Comment by web-padawan** [comment]
Below are the results of first page load in Chrome 71:

## Before (ES5)

Load: 2.00 s

<img width="581" alt="screen shot 2019-01-07 at 8 16 12" src="https://user-images.githubusercontent.com/10589913/50751974-cbf69b00-1254-11e9-9ab8-3f0e2452a08d.png">

## After (ES6)

Load: 1.35 s

<img width="579" alt="screen shot 2019-01-07 at 8 17 00" src="https://user-images.githubusercontent.com/10589913/50752019-f3e5fe80-1254-11e9-9fc8-d592b13637f3.png">
